---
- name: Install Java 21
  dnf:
    name: java-21-amazon-corretto-headless
    state: present

- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present

- name: Install Docker
  dnf:
    name: docker
    state: present

- name: Install Maven
  dnf:
    name: maven
    state: present

- name: Install Git
  dnf:
    name: git
    state: present

- name: Add jenkins to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Fix docker socket permissions
  file:
    path: /var/run/docker.sock
    mode: '0666'

- name: Start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
