---
- name: Add Corretto repo
  command: rpm --import https://yum.corretto.aws/corretto.key

- name: Add Corretto yum repo
  get_url:
    url: https://yum.corretto.aws/corretto.repo
    dest: /etc/yum.repos.d/corretto.repo

- name: Install Java 21
  command: yum install -y java-21-amazon-corretto-devel
  args:
    creates: /usr/lib/jvm/java-21-amazon-corretto

- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Jenkins
  command: yum install -y jenkins
  args:
    creates: /usr/bin/jenkins

- name: Install Docker
  command: yum install -y docker
  args:
    creates: /usr/bin/docker

- name: Install Maven
  command: yum install -y maven
  args:
    creates: /usr/bin/mvn

- name: Install Git
  command: yum install -y git
  args:
    creates: /usr/bin/git

- name: Add jenkins to docker group
  command: usermod -aG docker jenkins

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Fix docker socket permissions
  file:
    path: /var/run/docker.sock
    mode: '0666'
