[jenkins]
3.83.84.193 ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/devops-key.pem

[k8s_master]
52.91.213.62 ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/devops-key.pem

[k8s_workers]
3.85.160.230 ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/devops-key.pem
18.207.0.149 ansible_user=ec2-user ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/devops-key.pem
