---
- name: Install Docker
  command: yum install -y docker
  args:
    creates: /usr/bin/docker

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install awscli
  command: yum install -y awscli
  args:
    creates: /usr/bin/aws

- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Download kops
  get_url:
    url: https://github.com/kubernetes/kops/releases/download/v1.28.0/kops-linux-amd64
    dest: /usr/local/bin/kops
    mode: '0755'
